### ISSUE TITLE
n-aksif-n.github.io/MineColab_Improved is down

### ISSUE THREAD

**Issue by Myuui** [N-aksif-N/MineColab_Improved#11]
404 error of website

**To Reproduce**
1. Go to https://n-aksif-n.github.io/MineColab_Improved/

**Expected behavior**
A working Website

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS:
 - Browser: 
 - Version:

**Smartphone (please complete the following information):**
 - Device: S22
 - OS: Android 14
 - Browser: Chrome
 - Version: 129.0.6668.81

**Additional context**
/

**Comment by apulise** [comment]
Hey. We actually changed our wiki page to [this one](https://minecolabimproved.wiki.gg/es/wiki/MineColab_Improved_Wiki). It is in Spanish but you can translate it. 
Also, keep in mind that the releases from this GitHub are out to date. New ones can be downloaded from the [official discord](https://discord.gg/hRENyTdDfd) of the project.
