### ISSUE TITLE
Can you help me create a template for forge 1.16.5 - 36.2.42?

### ISSUE THREAD

**Issue by AumJixs** [N-aksif-N/MineColab_Improved#2]

**Comment by N-aksif-N** [comment]
Oh ye, my bad. Well in our file, you can install server for forge 1.16.5 - 36.2.42 in software function
Image:
![image](https://github.com/N-aksif-N/MineColab_Improved/assets/162333410/0b6978b1-d17f-4148-a2fe-c032dead36ca)
Guide:
1. Go to the software function
2. Change the server_type variable to forge (click and choose the dropdown)
3. Go to the choose server function 
4. Run it and choose your server which was installed forge.jar
5. Run the server again by using the console function.

**Comment by N-aksif-N** [comment]
Also, the software function will automatically install the latest version for each server_type. So if you want to run it in other versions (not recommended), you have to run it by hand.
