### ISSUE TITLE
The server opens in the vanilla version and not in the forge

### ISSUE THREAD

**Issue by PabloDevh** [N-aksif-N/MineColab_Improved#3]
![Captura de pantalla 2024-06-02 164935](https://github.com/N-aksif-N/MineColab_Improved/assets/119813653/8e171160-182c-44ac-a112-caceb4e8ab86)

**Comment by N-aksif-N** [comment]
I have fixed it in [my discord](https://discord.gg/XE9JapTMqm). And I will release it in the new release package (version 0.1.2)

**Comment by N-aksif-N** [comment]
Sorry for my late. :<

**Comment by PabloDevh** [comment]
There's nothing wrong with being late, it's better than not responding.
