### ISSUE TITLE
the server asks me to create the tunnel again

### ISSUE THREAD

**Issue by Xelz02** [N-aksif-N/MineColab_Improved#4]
**Describe the bug**
I already made the server and ran it, i was able to play and everything, but today when i was about to start it it asked me to create the tunnel again, i tought i just needed to do it once (i used playit btw), did i do something wrong?

**To Reproduce**
Just run the server on the ▶ or 🛑 Console

**Expected behavior**
Just start running the server normally

**Screenshots**
![image](https://github.com/N-aksif-N/MineColab_Improved/assets/174724167/5eac2de3-c7ef-43cb-9da9-1e23c80e1c14)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version dunno tbh

**Additional context**
I also used mods but i dont think thats the problem here

**Comment by N-aksif-N** [comment]
No. Google Collab produces us a variety of devices. Therefore, once we connect to the Minecolab_Improved, Google Collab will serve us the **different** OS so that we need to make another tunnel.

**Comment by N-aksif-N** [comment]
It's fine. Join my [discord](https://discord.gg/XE9JapTMqm) for more help?

**Comment by N-aksif-N** [comment]
According to Google collab, they serve not only us but also for other people. So, I think after we stop using the Gcollab or more specific Minecolab_Improved file . They will destroy/delete the data. Although, we can save data to our Google drive which I used to save data such as .txt file, the playit always put it in sw else. I will consider to bring the data to our Google drive but not now.
