### ISSUE TITLE
how do i change my Ngrok ID if i already added one

### ISSUE THREAD

**Issue by NotShinx** [N-aksif-N/MineColab_Improved#5]
im having problems with Ngrok so i thought about changing my Ngrok ID to solve the problems but i cant find any place to put my new ID or remove the existing one. Pls help.

**Comment by N-aksif-N** [comment]
In the minecraft folder, there is a server_list.txt.
![trashed-1723284130-Screenshot_20240711-170042](https://github.com/N-aksif-N/MineColab_Improved/assets/162333410/ed7c65e3-9ca8-4b53-8474-e282708c52f9)

This will include the ngrok authtoken 
![Screenshot_20240711-170359](https://github.com/N-aksif-N/MineColab_Improved/assets/162333410/6b3b0ccc-c95f-427a-a617-3a324e3b3477)


Change it.
