### ISSUE TITLE
How to alternate between servers

### ISSUE THREAD

**Issue by Cetropalo** [N-aksif-N/MineColab_Improved#6]
So the tittle sais it all how can I do that.

**Comment by N-aksif-N** [comment]
![image](https://github.com/user-attachments/assets/d9d3f6e2-8487-4e9a-bb70-f4425199900e)

See this function? Run it and follow the prompt.
Also join the [discord](https://discord.gg/F9nPJTn7Nu) for more help

**Comment by N-aksif-N** [comment]
Sorry for open it, but it will allow more people to know this 😄

**Comment by Cetropalo** [comment]
literally 5 mins later I figured it out xd
